### PR TITLE
Fix some bugs

### LINKED ISSUE #41: Storage without reservation binary variables cannot provide reserves
See here:
https://github.com/NREL-Sienna/StorageSystemsSimulations.jl/blob/87920a600f69d072fc98a584818ded5c0be90d8c/src/storage_models.jl#L221

```
ERROR: InfrastructureSystems.InvalidValue("variable ReservationVariable__EnergyReservoirStorage is not stored. [Symbol(\"AncillaryServiceVariableCharge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Sierra Spin\"), :StorageRegularizationVariableDischarge__EnergyReservoirStorage, :StorageRegularizationVariableCharge__EnergyReservoirStorage, Symbol(\"AncillaryServiceVariableCharge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Nevada Power Regulation\"), :StartVariable__ThermalStandard, :EnergyVariable__EnergyReservoirStorage, Symbol(\"AncillaryServiceVariableCharge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Sierra Regulation\"), :OnVariable__ThermalStandard, :StopVariable__ThermalStandard, Symbol(\"AncillaryServiceVariableDischarge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Sierra Regulation\"), Symbol(\"AncillaryServiceVariableDischarge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Nevada Power Regulation\"), :ActivePowerVariable__HydroDispatch, Symbol(\"AncillaryServiceVariableCharge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Nevada Power Spin\"), :ActivePowerInVariable__EnergyReservoirStorage, :ActivePowerOutVariable__EnergyReservoirStorage, :FlowActivePowerVariable__AreaInterchange, :ActivePowerVariable__RenewableDispatch, :ActivePowerVariable__ThermalStandard, Symbol(\"AncillaryServiceVariableDischarge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Sierra Spin\"), Symbol(\"AncillaryServiceVariableDischarge__EnergyReservoirStorage__VariableReserve{ReserveUp}_Nevada Power Spin\")]")
Stacktrace:
  [1] get_variable(container::PowerSimulations.OptimizationContainer, key::InfrastructureSystems.Optimization.VariableKey{…})
    @ PowerSimulations ~/2024_Repos/PowerSimulations.jl/src/core/optimization_container.jl:989
  [2] get_variable (repeats 2 times)
    @ ~/2024_Repos/PowerSimulations.jl/src/core/optimization_container.jl:1000 [inlined]
  [3] add_reserve_range_constraint_with_deployment!(container::PowerSimulations.OptimizationContainer, ::Type{…}, ::Type{…}, devices::InfrastructureSystems.FlattenIteratorWrapper{…}, model::DeviceModel{…}, ::NetworkModel{…})
    @ StorageSystemsSimulations ~/.julia/packages/StorageSystemsSimulations/OfSi6/src/storage_models.jl:221
```

### PR DESCRIPTION
**Pull request by rodrigomha**
Closes #41 and #44

### CODE REVIEW

File: src/StorageSystemsSimulations.jl [hunk 1]
```diff
@@ -53,6 +54,7 @@ import DataStructures: OrderedDict
 const MOI = MathOptInterface
 const PSI = PowerSimulations
 const PSY = PowerSystems
+const PNM = PowerNetworkMatrices
```
Comment (jd-lara) [inline src/StorageSystemsSimulations.jl:57]: Lets do this to avoid dependency hell 

```suggestion
const PNM = PSI.PNM
```

File: Project.toml [hunk 2]
```diff
@@ -11,17 +11,19 @@ InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
 JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
 LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
 MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
+PowerNetworkMatrices = "bed98974-b02a-5e2f-9fe0-a103f5c450dd"
```
Comment (jd-lara) [inline Project.toml:14]: remove from here
